# Setup
title: Stuff Writer
tagline: I have a lot of stuff.
url: https://stuffwriter.com
paginate: 10
baseurl: ""
permalink: :title/


+ markdown: CommonMark
+ commonmark:
+   options: ["SMART", "FOOTNOTES"]
+   extensions: ["strikethrough", "autolink", "table"]

kramdown:
    footnote_backlink: "&#10548;"
exclude:
  - .jekyll-cache
  
# Gems
plugins:
  - jekyll-paginate
  - jekyll-commonmark
  - jekyll-include-cache


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

keep_files: [assets]


sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jim Fitzsimmons
  url: https://twitter.com/tidyhusband
